version: '2.2'
services:

  postgres:
    restart: always
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=java_dev
    volumes:
      - '${WEBROOT}/docker/volumes/pg:/var/lib/postgresql'
    networks:
      - code-network

  java:
    restart: always
    ports:
      - "8080:8080"
    build:
      context: .
    depends_on:
      - postgres
    networks:
      - code-network

networks:
  code-network:
    driver: bridge