version: '2.2'
services:
  postgres:
    restart: always
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=java_dev
    volumes:
      - '${WEBROOT}/docker/volumes/pg:/var/lib/postgresql'
    networks:
      - code-network
networks:
  code-network:
    driver: bridge